PLEASE PLEASE PLEASE I FINALLY FIXED IT?
KQM-git/TCL pull request #77
Opened 2022-11-16 06:03 UTC by EmperorOfNuts

2022-11-18 09:34 UTC, Effab1e commented
if we are capitalizing 'e' in 'Energy recharge' then maybe change every instance of 'Energy recharge' to 'Energy Recharge' bc:
1 - It is capitalized in game
2 - Currently both Energy Recharge and Energy recharge can be found in the TCL.

2022-11-19 02:33 UTC, paichlear requested changes
comments are things that appear more than once
suggestions are things that vary on a case-to-case basis
(for the most part)

2022-11-19 18:18 UTC, EmperorOfNuts commented on docs/characters/pyro/klee.md
> +* Can be cancelled before cooldown by **Sparks n&apos; Splash** to activate Skill triggered passives for free.
:OHNO:

2022-11-19 18:22 UTC, EmperorOfNuts commented on docs/enemy-data/automatons/ruin-cruiser.md
> +* By withdrawing its three orbitals and diverting all power to the head, it pushes itself back while also laying an energized Orb. This attack is performed when the player is close to the Ruin Cruise
there's nothing i can really do about these single out its just cringe and has to be changed manually, thank you pai😆

2022-11-19 18:23 UTC, EmperorOfNuts commented on docs/enemy-data/automatons/ruin-grader.md
> +| Death        | 1 Orb           | common  |
okay whoever wrote this originally needs to go see a doctor

2022-11-19 18:24 UTC, EmperorOfNuts commented on docs/enemy-data/bosses/overworld-bosses/hypostases/hypostases.md
> +* When HP is low (approx. 5%), moves to the center of the arena and forms 4 large floating Anemo Orbs along with several updrafts. After some time , absOrbs any Anemo Orbs that remain, healing a larg
oh my lord

2022-11-19 18:26 UTC, EmperorOfNuts commented on docs/enemy-data/bosses/overworld-bosses/regisvines/regisvines.md
>  * Slams its' head on the ground and sweeps it 180 degrees.
whoever wrote all of those I...

2022-11-19 18:27 UTC, EmperorOfNuts commented on docs/enemy-data/bosses/weekly-bosses/azhdaha.md
> +  * Cryo: Damage type converted to Cryo. Slower tha Normal Tail Slam, but will summon several Ice Spikes around the impact area that will explode twice. (Phase 3)
HAHHAHAHAHAH MY REGEX WORKAROUND DID NOT WORK SMOGE

2022-11-19 18:42 UTC, EmperorOfNuts commented on docs/evidence/characters/anemo/kaedehara-kazuha.md
> +Kazuha's E > plunge Anemo infusion/conversion is not overtaken by weapon infuson from the likes of bennett or chongyun.
I mean instances like this is is just so stupid

2022-11-19 18:45 UTC, EmperorOfNuts commented on docs/evidence/characters/anemo/sucrose.md
> +### Gambler's 4-Piece effect can stack with sacrificial weapons to refresh two of sucrose's Skill charges simultaneously
This is like stirring a hornet's nest since there are way too many of these things

2022-11-19 18:54 UTC, EmperorOfNuts commented on docs/evidence/characters/dendro/traveler-dendro.md
> +[Discussion](https://tickets.deeznuts.moe/transcripts/mc-base-ATK-buff)
wait this means i could have just used this to avoid...

2022-11-19 18:56 UTC, EmperorOfNuts commented on docs/evidence/characters/electro/fischl.md
> +### Fischl's C6 Procs 4-Piece Millelith
no, i tell the regex to fix the urls too.

2022-11-19 19:00 UTC, EmperorOfNuts commented on docs/evidence/characters/electro/fischl.md
> +### Fischl's C6 Procs 4-Piece Millelith
and i just searched for it its not linked anywhere in the TCL

2022-11-19 19:06 UTC, EmperorOfNuts commented on docs/evidence/combat-mechanics/damage/healing.md
> +[Video](https://youtu.be/yJMPaWKCCbA) Barbara with 9419 health, level 7 Skill, 4-Piece maidens, and Hydro resonance. Assuming outgoing and incoming are additive, Barbara would heal for `((9419 * 0.06
impossible to regex with how many abbreviated ones that exist. Cannot tell the difference unless read through 1 by 1 thanks to Anemo RES now meaning either resistance shred or resonance.

2022-11-19 19:09 UTC, EmperorOfNuts commented on docs/evidence/combat-mechanics/elemental-effects/transformative-reactions.md
> +### What if after an Electro-Charged trigger or tick, &lt;0.5s remains from either the Electro or Hydro auras?
Fine to leave as is, no links in TCL.

2022-11-19 19:12 UTC, EmperorOfNuts commented on docs/evidence/combat-mechanics/elemental-effects/transformative-reactions.md
>  [https://youtu.be/iPvFviMCX1c](https://youtu.be/iPvFviMCX1c)
Nothing like cleaning up the really really old evidence linking style...

2022-11-19 19:24 UTC, EmperorOfNuts commented on docs/evidence/combat-mechanics/enemy-mechanics/enemy-interactions.md
> +38 sucrose attacks: [YouTube](https://youtu.be/Fq0zpru1Ej4)
in general names of characters are super scuffed

2022-11-19 19:25 UTC, EmperorOfNuts commented on docs/evidence/combat-mechanics/enemy-mechanics/enemy-interactions.md
> +#### Polearm Charged Attacks Don't Register On Stunned Ruin Guards
doesnt exist anywhere in TCL

2022-11-19 19:26 UTC, EmperorOfNuts commented on docs/evidence/combat-mechanics/enemy-mechanics/enemy-shields.md
> +* Hydro armor: ~10 Electro-charged ticks
it was my replacement order issue

2022-11-19 19:26 UTC, EmperorOfNuts commented on docs/evidence/combat-mechanics/enemy-mechanics/enemy-shields.md
> +* Hydro on a Cryo fatui armor.
Bro

2022-11-19 19:37 UTC, EmperorOfNuts commented on docs/evidence/combat-mechanics/energy.md
> +Elemental Particle production sheet here: [https://docs.google.com/spreadsheets/d/1G05DxDSjtBzj4PZtVjGRA4ATq76HPZa6e4kHVWS6mrA/edit\#gid=0](https://docs.google.com/spreadsheets/d/1G05DxDSjtBzj4PZtVjG
\[https:\/\/[a-z, .]*google[a-z, A-Z, .\/?=&-_]*\]

2022-11-19 19:54 UTC, EmperorOfNuts commented on docs/evidence/combat-mechanics/energy.md
> +Elemental Particle production sheet here: [https://docs.google.com/spreadsheets/d/1G05DxDSjtBzj4PZtVjGRA4ATq76HPZa6e4kHVWS6mrA/edit\#gid=0](https://docs.google.com/spreadsheets/d/1G05DxDSjtBzj4PZtVjG
wait but it deosnt work for google ones since they are stuck OMEGA

2022-11-19 20:14 UTC, EmperorOfNuts commented on docs/evidence/general-mechanics/bugs.md
> +Also, by climbing into a firework precisely placed on Geo traveler's rock, it is possible to force the character into a 45 degree angle and plunge off, to the same effects as horizon tech, but at 45
lol it was just these 2 instances in the evidence vault

2022-11-19 20:15 UTC, EmperorOfNuts commented on docs/evidence/general-mechanics/bugs.md
> +**Evidence:** [Gif](https://imgur.com/OUu1msK) [Gif](https://imgur.com/LsbvMJE) [Gif](https://imgur.com/6LG5Weq) [Gif](https://imgur.com/bssKdg2) [Gif](https://imgur.com/xjG8lzt) [Gif](https://imgur.
wwhat in the

2022-11-23 23:27 UTC, merged